In [1]:
import pandas as pd
import yaml
import importlib
import etl.normalization as normalization
importlib.reload(normalization)
from etl.typecasting import apply_schema_types, verify_schema_types
from etl.validator import add_range_and_allowed_flags, add_mandatory_flags

In [2]:
with open(r"hf_schema.yaml", "r", encoding="utf-8") as f:
    schema = yaml.safe_load(f)

schema

{'version': '1.0',
 'schema_id': 'heatflow:v1',
 'name': 'heat_flow_db_complete',
 'normalization': {'string': {'trim': True,
   'collapse_space': True,
   'case_insensitive': True,
   'enforce_brackets': True,
   'normalize_separator': True,
   'missing_tokens': ['', '-', 'NA', '<NA>', 'none', 'null']},
  'numeric': {'decimal_comma_to_dot': True,
   'strip_thousands_separators': [' '],
   'missing_tokens': ['', 'NA', '<NA>', '-']}},
 'core': {'ID': {'dtype': 'int64', 'unique': True, 'min': 1},
  'Obligation': {'dtype': 'string', 'allowed': ['M', 'R', 'O', '-']},
  'Level': {'dtype': 'string', 'allowed': ['Parent', 'Child', 'Admin']}},
 'columns': {'P1': {'dtype': 'float64',
   'range': [-999999.9, 999999.9],
   'obligation': 'M',
   'comment': 'HF Value'},
  'P2': {'dtype': 'float64',
   'range': [0.0, 999999.9],
   'obligation': 'M',
   'comment': 'HF Uncertainty'},
  'P3': {'dtype': 'string', 'obligation': 'M', 'comment': 'Name'},
  'P4': {'dtype': 'float64',
   'range': [-90.0, 90.0],
   'obligation': 'M',
   'comment': 'Latitude'},
  'P5': {'dtype': 'float64',
   'range': [-180.0, 180.0],
   'obligation': 'M',
   'comment': 'Longitude'},
  'P6': {'dtype': 'float64',
   'range': [-12000.0, 9000.0],
   'obligation': 'M',
   'comment': 'Elevation'},
  'P7': {'dtype': 'list[string]',
   'allowed': ['[Onshore (continental)]',
    '[Onshore (lake-river-etc.)]',
    '[Offshore (continental)]',
    '[Offshore (marine)]',
    '[Other (specify in comments)]',
    '[unspecified]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Location Type (multi-select)'},
  'P8': {'dtype': 'string',
   'obligation': 'M',
   'comment': 'Comments (Parent level)'},
  'P9': {'dtype': 'string',
   'allowed': ['Yes', 'No', '[unspecified]'],
   'obligation': 'R',
   'comment': 'Correction HP'},
  'P10': {'dtype': 'float64',
   'range': [-12000.0, 9000.0],
   'obligation': 'R',
   'comment': 'Total MD'},
  'P11': {'dtype': 'float64',
   'range': [-12000.0, 9000.0],
   'obligation': 'R',
   'comment': 'TVD'},
  'P12': {'dtype': 'list[string]',
   'allowed': ['[Drilling]',
    '[Mining]',
    '[Tunneling]',
    '[Probing (onshore-lake-river-etc.)]',
    '[Probing (offshore-ocean)]',
    '[Drilling-Clustering]',
    '[Probing-Clustering]',
    '[Indirect (GTM-BSR-CPD-etc.)]',
    '[Other (specify in comments)]',
    '[unspecified]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Type of Exploration Method (multi-select)'},
  'P13': {'dtype': 'list[string]',
   'allowed': ['[Hydrocarbon]',
    '[Underground storage]',
    '[Geothermal]',
    '[Groundwater]',
    '[Mapping]',
    '[Research]',
    '[Mining]',
    '[Tunneling]',
    '[Other (specify in comments)]',
    '[unspecified]'],
   'obligation': 'R',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Exploration Purpose (multi-select)'},
  'C1': {'dtype': 'float64',
   'range': [-999999.9, 999999.9],
   'obligation': 'M',
   'comment': 'HF Value (Child level)'},
  'C2': {'dtype': 'float64',
   'range': [0.0, 999999.9],
   'obligation': 'R',
   'comment': 'HF Uncertainty (Child level)'},
  'C3': {'dtype': 'list[string]',
   'allowed': ['[Interval method]',
    '[Bullard method]',
    '[Boot-strapping method]',
    '[Other numerical computations]',
    '[Other (specify in comments)]',
    '[unspecified]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'HF Method (multi-select)'},
  'C4': {'dtype': 'float64',
   'range': [0.0, 19999.9],
   'obligation': 'M',
   'comment': 'HF Interval Top'},
  'C5': {'dtype': 'float64',
   'range': [0.0, 19999.9],
   'obligation': 'M',
   'comment': 'HF Interval Bottom'},
  'C6': {'dtype': 'float64',
   'range': [0.0, 999.9],
   'obligation': 'M',
   'comment': 'Penetration Depth'},
  'C7': {'dtype': 'string',
   'obligation': 'M',
   'comment': 'Primary publication reference'},
  'C8': {'dtype': 'list[string]',
   'obligation': 'R',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Primary reference (multi-entry)'},
  'C9': {'dtype': 'string',
   'allowed': ['[Yes]', '[No]'],
   'obligation': 'M',
   'comment': 'Relevant Child'},
  'C10': {'dtype': 'list[string]',
   'obligation': 'R',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Comments (Child level; multi-entry)'},
  'C11': {'dtype': 'string',
   'allowed': ['[Considered - p]',
    '[Considered - T]',
    '[Considered - pT]',
    '[Not considered]',
    '[unspecified]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Flag: situ thermal properties considered (p, T, pT)'},
  'C12': {'dtype': 'string',
   'allowed': ['[Tilt corrected]',
    '[Drift corrected]',
    '[Not corrected]',
    '[Corrected (specify in comments)]',
    '[unspecified]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Flag: temperature corrections'},
  'C13': {'dtype': 'string',
   'allowed': ['[Present and corrected]',
    '[Present and not corrected]',
    '[Present not significant]',
    '[Not recognized]',
    '[unspecified]'],
   'obligation': 'R',
   'comment': 'Flag: sedimentation corrections'},
  'C14': {'dtype': 'string',
   'allowed': ['[Present and corrected]',
    '[Present and not corrected]',
    '[Present not significant]',
    '[Not recognized]',
    '[unspecified]'],
   'obligation': 'R',
   'comment': 'Flag: erosion corrections'},
  'C15': {'dtype': 'string',
   'allowed': ['[Present and corrected]',
    '[Present and not corrected]',
    '[Present not significant]',
    '[Not recognized]',
    '[unspecified]'],
   'obligation': 'M',
   'comment': 'Flag: topographic corrections'},
  'C16': {'dtype': 'string',
   'allowed': ['[Present and corrected]',
    '[Present and not corrected]',
    '[Present not significant]',
    '[Not recognized]',
    '[unspecified]'],
   'obligation': 'M',
   'comment': 'Flag: paleoclimatic corrections'},
  'C17': {'dtype': 'string',
   'allowed': ['[Present and corrected]',
    '[Present and not corrected]',
    '[Present not significant]',
    '[Not recognized]',
    '[unspecified]'],
   'obligation': 'M',
   'comment': 'Flag: heat refraction effets corrections',
   'C18': None,
   'C19': None},
  'C20': {'dtype': 'list[string]',
   'allowed': ['[Expedition-Cruise number]',
    '[R/V Ship]',
    '[D/V Platform]',
    '[D/V Glomar Challenger]',
    '[D/V JOIDES Resolution]',
    '[Other (specify in comments)]',
    '[unspecified]'],
   'obligation': 'R',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Platform, vessel, or expedition'},
  'C21': {'dtype': 'list[string]',
   'allowed': ['[Single Steel probe (Bullard)]',
    '[Single Steel probe (Bullard) in-situ TC]',
    '[Violin-Bow probe (Lister)]',
    '[Outrigger probe (Von Herzen) in-situ TC]',
    '[Outrigger probe (Haenel) in-situ TC]',
    '[Outrigger probe (Ewing) with corer]',
    '[Outrigger probe (Ewing) without corer]',
    '[Outrigger probe (Lister) with corer]',
    '[Outrigger probe (autonomous) without corer]',
    '[Outrigger probe (autonomous) with corer]',
    '[Submersible probe]',
    '[Other (specify in comments)]',
    '[unspecified]'],
   'obligation': 'R',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Probe type'},
  'C22': {'dtype': 'float64',
   'range': [0.0, 99.9],
   'obligation': 'R',
   'comment': 'Probe length'},
  'C23': {'dtype': 'float64',
   'range': [0.0, 99.9],
   'obligation': 'M',
   'comment': 'Probe tilt'},
  'C24': {'dtype': 'float64',
   'range': [-273.15, 999.99],
   'obligation': 'O',
   'comment': 'Bottom water temperature'},
  'C25': {'dtype': 'list[string]',
   'allowed': ['acidic_igneous_material',
    'acidic_igneous_rock',
    'alkali_feldspar_granite',
    'alkali_feldspar_rhyolite',
    'alkali_feldspar_syenite',
    'alkali_feldspar_syenitic_rock',
    'alkali_feldspar_trachyte',
    'alkali_feldspar_trachytic_rock',
    'alkali-olivine_basalt',
    'amphibolite',
    'andesite',
    'anorthosite',
    'anorthositic_rock',
    'anthracite_coal',
    'anthropogenic_material',
    'anthropogenic_unconsolidated_material',
    'aphanite',
    'aplite',
    'arenite',
    'ash_and_lapilli',
    'ash_breccia_bomb_or_block_tephra',
    'ash_tuff_lapillistone_and_lapilli_tuff',
    'basalt',
    'basanite',
    'basanitic_foidite',
    'basic_igneous_material',
    'basic_igneous_rock',
    'bauxite',
    'biogenic_sediment',
    'biogenic_silica_sedimentary_rock',
    'bituminous_coal',
    'boninite',
    'boulder_gravel_size_sediment',
    'boundstone',
    'breccia',
    'breccia_gouge_series',
    'calcareous_carbonate_sediment',
    'calcareous_carbonate_sedimentary_material',
    'calcareous_carbonate_sedimentary_rock',
    'carbonate_mud',
    'carbonate_mudstone',
    'carbonate_ooze',
    'carbonate_rich_mud',
    'carbonate_rich_mudstone',
    'carbonate_sediment',
    'carbonate_sedimentary_material',
    'carbonate_sedimentary_rock',
    'carbonate_wackestone',
    'carbonatite',
    'cataclasite_series',
    'chalk',
    'chemical_sedimentary_material',
    'chlorite_actinolite_epidote_metamorphic_rock',
    'clastic_sediment',
    'clastic_sedimentary_material',
    'clastic_sedimentary_rock',
    'clay',
    'claystone',
    'coal',
    'cobble_gravel_size_sediment',
    'composite_genesis_material',
    'composite_genesis_rock',
    'compound_material',
    'clastic_conglomerate',
    'crystalline_carbonate',
    'dacite',
    'diamictite',
    'diamicton',
    'diorite',
    'dioritic_rock',
    'dioritoid',
    'doleritic_rock',
    'dolostone',
    'dolomitic_or_magnesian_sedimentary_material',
    'dolomitic_or_magnesian_sedimentary_rock',
    'dolomitic_sediment',
    'duricrust',
    'eclogite',
    'evaporite',
    'exotic_alkaline_rock',
    'exotic_composition_igneous_rock',
    'exotic_evaporite',
    'fault_related_material',
    'fine_grained_igneous_rock',
    'foid_bearing_alkali_feldspar_syenite',
    'foid_bearing_alkali_feldspar_trachyte',
    'foid_bearing_anorthosite',
    'foid_bearing_diorite',
    'foid_bearing_gabbro',
    'foid_bearing_latite',
    'foid_bearing_monzodiorite',
    'foid_bearing_monzogabbro',
    'foid_bearing_monzonite',
    'foid_bearing_syenite',
    'foid_bearing_trachyte',
    'foid_diorite',
    'foid_dioritoid',
    'foid_gabbro',
    'foid_gabbroid',
    'foid_monzodiorite',
    'foid_monzogabbro',
    'foid_monzosyenite',
    'foid_syenite',
    'foid_syenitoid',
    'foidite',
    'foiditoid',
    'foidolite',
    'foliated_metamorphic_rock',
    'fragmental_igneous_material',
    'fragmental_igneous_rock',
    'framestone',
    'gabbro',
    'gabbroic_rock',
    'gabbroid',
    'generic_conglomerate',
    'generic_mudstone',
    'generic_sandstone',
    'glass_rich_igneous_rock',
    'glassy_igneous_rock',
    'glaucophane_lawsonite_epidote_metamorphic_rock',
    'gneiss',
    'grainstone',
    'granite',
    'granitoid',
    'granodiorite',
    'granofels',
    'granulite',
    'gravel',
    'gravel_size_sediment',
    'rock_gypsum_or_anhydrite',
    'high_magnesium_fine_grained_igneous_rocks',
    'hornblendite',
    'hornfels',
    'hybrid_sediment',
    'hybrid_sedimentary_rock',
    'igneous_material',
    'igneous_rock',
    'impact_generated_material',
    'impure_calcareous_carbonate_sediment',
    'impure_carbonate_sediment',
    'impure_carbonate_sedimentary_rock',
    'impure_dolostone',
    'impure_dolomitic_sediment',
    'impure_limestone',
    'intermediate_composition_igneous_material',
    'intermediate_composition_igneous_rock',
    'iron_rich_sediment',
    'iron_rich_sedimentary_material',
    'iron_rich_sedimentary_rock',
    'kalsilitic_and_melilitic_rock',
    'komatiitic_rock',
    'latite',
    'latitic_rock',
    'lignite',
    'limestone',
    'marble',
    'material_formed_in_surficial_environment',
    'metamorphic_rock',
    'metasomatic_rock',
    'mica_schist',
    'migmatite',
    'monzodiorite',
    'monzodioritic_rock',
    'monzogabbro',
    'monzogabbroic_rock',
    'monzogranite',
    'monzonite',
    'monzonitic_rock',
    'mud',
    'mud_size_sediment',
    'clastic_mudstone',
    'mylonitic_rock',
    'natural_unconsolidated_material',
    'non_clastic_siliceous_sediment',
    'non_clastic_siliceous_sedimentary_material',
    'non_clastic_siliceous_sedimentary_rock',
    'ooze',
    'organic_bearing_mudstone',
    'organic_rich_sediment',
    'organic_rich_sedimentary_material',
    'organic_rich_sedimentary_rock',
    'orthogneiss',
    'packstone',
    'paragneiss',
    'peat',
    'pebble_gravel_size_sediment',
    'pegmatite',
    'peridotite',
    'phaneritic_igneous_rock',
    'phonolilte',
    'phonolitic_basanite',
    'phonolitic_foidite',
    'phonolitic_tephrite',
    'phonolitoid',
    'phosphate_rich_sediment',
    'phosphate_rich_sedimentary_material',
    'phosphorite',
    'phyllite',
    'phyllonite',
    'porphyry',
    'pure_calcareous_carbonate_sediment',
    'pure_carbonate_mudstone',
    'pure_carbonate_sediment',
    'pure_carbonate_sedimentary_rock',
    'pure_dolomitic_sediment',
    'pyroclastic_material',
    'pyroclastic_rock',
    'pyroxenite',
    'quartz_alkali_feldspar_syenite',
    'quartz_alkali_feldspar_trachyte',
    'quartz_anorthosite',
    'quartz_diorite',
    'quartz_gabbro',
    'quartz_latite',
    'quartz_monzodiorite',
    'quartz_monzogabbro',
    'quartz_monzonite',
    'quartz_rich_igneous_rock',
    'quartz_syenite',
    'quartz_trachyte',
    'quartzite',
    'residual_material',
    'rhyolite',
    'rhyolitoid',
    'rock',
    'rock_salt',
    'sand',
    'sand_size_sediment',
    'clastic_sandstone',
    'sapropel',
    'schist',
    'sediment',
    'sedimentary_material',
    'sedimentary_rock',
    'serpentinite',
    'shale',
    'silicate_mud',
    'silicate_mudstone',
    'siliceous_ooze',
    'silt',
    'siltstone',
    'skarn',
    'slate',
    'spilite',
    'syenite',
    'syenitic_rock',
    'syenitoid',
    'syenogranite',
    'tephra',
    'tephrite',
    'tephritic_foidite',
    'tephritic_phonolite',
    'tephritoid',
    'tholeiitic_basalt',
    'tonalite',
    'trachyte',
    'trachytic_rock',
    'trachytoid',
    'travertine',
    'tuff_breccia_agglomerate_or_pyroclastic_breccia',
    'tuffite',
    'ultrabasic_igneous_rock',
    'ultramafic_igneous_rock',
    'unconsolidated_material',
    'wacke'],
   'obligation': 'O',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Lithology'},
  'C26': {'dtype': 'list[string]',
   'allowed': ['Aalenian',
    'Aeronian',
    'Albian',
    'Anisian',
    'Aptian',
    'Aquitanian',
    'Archean',
    'Artinskian',
    'Asselian',
    'Bajocian',
    'Barremian',
    'Bartonian',
    'Bashkirian',
    'Bathonian',
    'Berriasian',
    'Burdigalian',
    'Calabrian',
    'Callovian',
    'Calymmian',
    'Cambrian',
    'CambrianSeries2',
    'CambrianSeries3',
    'CambrianStage10',
    'CambrianStage2',
    'CambrianStage3',
    'CambrianStage4',
    'CambrianStage5',
    'Campanian',
    'Capitanian',
    'Carboniferous',
    'Carnian',
    'Cenomanian',
    'Cenozoic',
    'Changhsingian',
    'Chattian',
    'MiddlePleistocene',
    'Cisuralian',
    'Coniacian',
    'Cretaceous',
    'Cryogenian',
    'Danian',
    'Dapingian',
    'Darriwilian',
    'Devonian',
    'Drumian',
    'LowerCretaceous',
    'LowerDevonian',
    'LowerJurassic',
    'LowerMississippian',
    'LowerOrdovician',
    'LowerPennsylvanian',
    'LowerTriassic',
    'Ectasian',
    'Ediacaran',
    'Eifelian',
    'Emsian',
    'Eoarchean',
    'Eocene',
    'Famennian',
    'Floian',
    'Fortunian',
    'Frasnian',
    'Furongian',
    'Gelasian',
    'Givetian',
    'Gorstian',
    'Greenlandian',
    'Guadalupian',
    'Guzhangian',
    'Gzhelian',
    'Hadean',
    'Hauterivian',
    'Hettangian',
    'Hirnantian',
    'Holocene',
    'Homerian',
    'Induan',
    'Ionian',
    'Jiangshanian',
    'Jurassic',
    'Kasimovian',
    'Katian',
    'Kimmeridgian',
    'Kungurian',
    'Ladinian',
    'Langhian',
    'UpperCretaceous',
    'UpperDevonian',
    'UpperJurassic',
    'UpperMississippian',
    'UpperOrdovician',
    'UpperPennsylvanian',
    'UpperPleistocene',
    'UpperTriassic',
    'Llandovery',
    'Lochkovian',
    'Lopingian',
    'Ludfordian',
    'Ludlow',
    'Lutetian',
    'Maastrichtian',
    'Meghalayan',
    'Mesoarchean',
    'Mesoproterozoic',
    'Mesozoic',
    'Messinian',
    'Miaolingian',
    'MiddleDevonian',
    'MiddleJurassic',
    'MiddleMississippian',
    'MiddleOrdovician',
    'MiddlePennsylvanian',
    'MiddleTriassic',
    'Miocene',
    'Mississippian',
    'Moscovian',
    'Neoarchean',
    'Neogene',
    'Neoproterozoic',
    'Norian',
    'Northgrippian',
    'Olenekian',
    'Oligocene',
    'Ordovician',
    'Orosirian',
    'Oxfordian',
    'Paibian',
    'Paleoarchean',
    'Paleocene',
    'Paleogene',
    'Paleoproterozoic',
    'Paleozoic',
    'Pennsylvanian',
    'Permian',
    'Phanerozoic',
    'Piacenzian',
    'Pleistocene',
    'Pliensbachian',
    'Pliocene',
    'Pragian',
    'Precambrian',
    'Priabonian',
    'Pridoli',
    'Proterozoic',
    'Quaternary',
    'Rhaetian',
    'Rhuddanian',
    'Rhyacian',
    'Roadian',
    'Rupelian',
    'Sakmarian',
    'Sandbian',
    'Santonian',
    'Selandian',
    'Serpukhovian',
    'Serravallian',
    'Sheinwoodian',
    'Siderian',
    'Silurian',
    'Sinemurian',
    'Statherian',
    'Stenian',
    'Telychian',
    'Terreneuvian',
    'Thanetian',
    'Tithonian',
    'Toarcian',
    'Tonian',
    'Tortonian',
    'Tournaisian',
    'Tremadocian',
    'Triassic',
    'Turonian',
    'Valanginian',
    'Visean',
    'Wenlock',
    'Wordian',
    'Wuchiapingian',
    'Wuliuan',
    'Ypresian',
    'Zanclean'],
   'obligation': 'O',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Stratigraphy'},
  'C27': {'dtype': 'float64',
   'range': [-99999.99, 99999.99],
   'obligation': 'M',
   'comment': 'Temperature gradient'},
  'C28': {'dtype': 'float64',
   'range': [-99999.99, 99999.99],
   'obligation': 'R',
   'comment': 'Temperature gradient uncertainty'},
  'C29': {'dtype': 'float64',
   'range': [-99999.99, 99999.99],
   'obligation': 'O',
   'comment': 'Corrected temperature gradient'},
  'C30': {'dtype': 'float64',
   'range': [-99999.99, 99999.99],
   'obligation': 'O',
   'comment': 'Corrected temperature gradient uncertainty'},
  'C31': {'dtype': 'list[string]',
   'allowed': ['[LOGeq]',
    '[LOGpert]',
    '[cLOG]',
    '[DTSeq]',
    '[DTSpert]',
    '[cDTS]',
    '[BHT]',
    '[cBHT]',
    '[HT-FT]',
    '[cHT-FT]',
    '[RTDeq]',
    '[RTDpert]',
    '[cRTD]',
    '[CPD]',
    '[XEN]',
    '[GTM]',
    '[BSR]',
    '[BLK]',
    '[ODTT-PC]',
    '[ODTT-TP]',
    '[GRT]',
    '[EGRT]',
    '[SUR]',
    '[unspecified]',
    '[Other (specify in comments)]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Temperature method (top, multi-select)'},
  'C32': {'dtype': 'list[string]',
   'allowed': ['[LOGeq]',
    '[LOGpert]',
    '[cLOG]',
    '[DTSeq]',
    '[DTSpert]',
    '[cDTS]',
    '[BHT]',
    '[cBHT]',
    '[HT-FT]',
    '[cHT-FT]',
    '[RTDeq]',
    '[RTDpert]',
    '[cRTD]',
    '[CPD]',
    '[XEN]',
    '[GTM]',
    '[BSR]',
    '[BLK]',
    '[ODTT-PC]',
    '[ODTT-TP]',
    '[GRT]',
    '[EGRT]',
    '[SUR]',
    '[unspecified]',
    '[Other (specify in comments)]'],
   'obligation': 'M',
   'multi_choice': True,
   'separator': ';',
   'comment': 'Temperature method (bottom, multi-select)',
   'C33': {'dtype': 'float64', 'range': [0.0, 99.99], 'obligation': 'R'},
   'C34': {'dtype': 'float64', 'range': [0.0, 99.99], 'obligation': 'R'},
   'C35': {'dtype': 'list[string]',
    'allowed': ['[Horner plot]',
     '[Cylinder source method]',
     '[Line source explosion method]',
     '[Inverse numerical modelling]',
     '[AAPG correction]',

In [3]:
df_raw = pd.read_excel(
    r"./testing/Abc_xyz_2008.xlsx",
    sheet_name=1,
    header=0,
    dtype=str 
)
print(df_raw.shape)
df_raw.head(10)

#check if everything is string 
df_raw.dtypes

(28, 71)

/opt/homebrew/Caskroom/miniconda/base/envs/thermo-env/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

ID    object
P1    object
P2    object
P3    object
P4    object
       ...
A4    object
A5    object
A6    object
A7    object
A8    object
Length: 71, dtype: object

In [4]:
# Tranfrom Excel to Parquet (all to string)
#divide into meta and data
df_raw["row_type"] = ["meta"] * 7 + ["data"] * (len(df_raw) - 7)
df_raw_str = df_raw.astype("string[pyarrow]")
#convert to parquet
df_raw_str.to_parquet(
    r"./testing/Abc_xyz_2008_raw.parquet",
    index=False)

In [5]:
# Load Parquet in as String 
df_raw_parquet_string = pd.read_parquet(
    r"./testing/Abc_xyz_2008_raw.parquet",
    dtype_backend="pyarrow"
).astype("string[pyarrow]")  
df_raw_parquet_string 

df_raw_parquet_string.dtypes

ID          string[pyarrow]
P1          string[pyarrow]
P2          string[pyarrow]
P3          string[pyarrow]
P4          string[pyarrow]
                 ...
A5          string[pyarrow]
A6          string[pyarrow]
A7          string[pyarrow]
A8          string[pyarrow]
row_type    string[pyarrow]
Length: 72, dtype: object

In [6]:
df_meta, df_data_norm = normalization.normalize_only_data_rows(
    df_raw_parquet_string,
    schema,
)

df_data_norm.dtypes

df_meta

,ID,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,C49,A1,A2,A3,A4,A5,A6,A7,A8,row_type
0,Obligation,M,M,M,M,M,M,M,R,R,...,O,-,-,-,-,-,-,-,-,meta
1,Domain,"B,S","B,S","B,S","B,S","B,S","B,S","B,S","B,S","B,S",...,"B,S",-,-,-,-,-,-,-,-,meta
2,Quality Relevance,U score,U score,-,-,-,M score,-,-,-,...,-,-,-,-,-,-,-,-,-,meta
3,Name,Heat-flow value,Heat-flow uncertainty,Site name,Geographical latitude,Geographical longitude,Elevation (Geographical),Basic geographical environment,General comments parent level,Flag heat production of the overburden (heat-f...,...,IGSN,Reviewer_name,Reviewer_comment,Review Date,Country,Region,Continent,Domain,Unique entry ID,meta
4,Short Name,q,q_uncertainty,name,lat_NS,long_EW,elevation,environment,p_comment,corr_HP_flag,...,Ref_ISGN,Reviewer_name,Reviewer_comment,Review_date,Country,Region,Continent,Domain,ID,meta
5,Unit,mW/m²,mW/m²,-,degrees,degrees,m,-,-,-,...,-,-,-,-,-,-,-,-,-,meta
6,Allowed range of values,"-999,999.9 – 999,999.9","0 – 999,999.9",-,-90.00000 – +90.00000,-180.00000 – +180.00000,-12000 – +9000,[Onshore (continental)],-,Yes,...,-,-,-,-,-,-,-,-,-,meta

In [7]:
# 2) type-cast only data rows
df_data_typed = apply_schema_types(df_data_norm, schema)



# 4) now dtypes here are your ground truth
print(df_data_typed.dtypes)
warns = verify_schema_types(df_data_typed, schema).query("status == 'OK'")
print(warns)

ID                    Int64
P1                  float64
P2                  float64
P3          string[pyarrow]
P4                  float64
                 ...
A5          string[pyarrow]
A6          string[pyarrow]
A7          string[pyarrow]
A8          string[pyarrow]
row_type    string[pyarrow]
Length: 72, dtype: object
   column expected   actual status
0      ID    int64    int64     OK
3      P1  float64  float64     OK
4      P2  float64  float64     OK
5      P3   string   string     OK
6      P4  float64  float64     OK
..    ...      ...      ...    ...
63     A4   string   string     OK
64     A5   string   string     OK
65     A6   string   string     OK
66     A7  string,   string     OK
67     A8   string   string     OK

[66 rows x 4 columns]

In [8]:
print(df_data_typed.dtypes.tail(10))   
#print(df_typed.head(5))

C49         string[pyarrow]
A1          string[pyarrow]
A2          string[pyarrow]
A3           datetime64[ns]
A4          string[pyarrow]
A5          string[pyarrow]
A6          string[pyarrow]
A7          string[pyarrow]
A8          string[pyarrow]
row_type    string[pyarrow]
dtype: object

In [9]:
df_data_typed["P7"]

7      [onshore-(continental)]
8      [onshore-(continental)]
9     [offshore-(continental)]
10         [offshore-(marine)]
11               [unspecified]
12     [onshore-(continental)]
13         [offshore-(marine)]
14     [onshore-(continental)]
15     [onshore-(continental)]
16     [onshore-(continental)]
17         [offshore-(marine)]
18         [offshore-(marine)]
19         [offshore-(marine)]
20         [offshore-(marine)]
21     [onshore-(continental)]
22     [onshore-(continental)]
23     [onshore-(continental)]
24     [onshore-(continental)]
25     [onshore-(continental)]
26     [onshore-(continental)]
27     [onshore-(continental)]
Name: P7, dtype: string

In [10]:
df_checked_mandatory = add_mandatory_flags(df_data_typed, schema)
df_checked_mandatory

,ID,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,C32__missing,C38__missing,C39__missing,C41__missing,C42__missing,C43__missing,C44__missing,C45__missing,C46__missing,C47__missing
7,1,39.35592,3.34944,chicheng 13,40.683333,115.500000,1300.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,True,False
8,2,33.49440,NaN,fanshan 103,40.200000,115.433333,750.0,[onshore-(continental)],<NA>,[unspecified],...,False,False,False,False,False,False,False,False,True,False
9,3,26.40000,0.65000,fangshan 46,40.166667,115.433333,875.0,[offshore-(continental)],mean hf,[unspecified],...,False,False,False,False,False,False,False,False,True,False
10,4,26.40000,0.65000,fangshan 46,40.166667,115.433333,875.0,[offshore-(marine)],mean hf,[unspecified],...,True,False,False,False,False,False,False,False,True,False
11,5,30.14496,NaN,chengde 10,40.583333,117.850000,NaN,[unspecified],<NA>,[unspecified],...,False,False,False,False,False,False,False,False,True,False
12,6,50.66028,3.34944,yanging 72-7,40.400000,116.266667,NaN,[onshore-(continental)],<NA>,[unspecified],...,False,False,False,False,False,False,False,False,True,False
13,7,56.52180,4.18680,yanging 72-5,40.416667,116.250000,528.0,[offshore-(marine)],<NA>,[unspecified],...,True,False,False,False,False,False,False,False,True,False
14,8,77.03712,1.67472,yanging 2,40.450000,115.933333,528.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,False,False
15,9,38.50000,NaN,caraiba,-9.470000,-39.835800,400.0,[onshore-(continental)],mean hf,[unspecified],...,False,False,False,False,False,False,False,False,False,True
16,10,51.00000,12.00000,jacobina,-11.250000,-40.500000,850.0,[onshore-(continental)],<NA>,[unspecifiedd],...,False,False,False,False,False,False,False,False,False,True
17,11,96.80000,37.40000,m45-300,62.058330,-25.253330,-1418.0,[offshore-(marine)],<NA>,[no],...,True,False,False,False,False,False,False,False,False,False
18,12,123.20000,47.00000,m45-302,62.103330,-25.350000,-1544.0,[offshore-(marine)],<NA>,<NA>,...,True,False,False,False,False,False,False,False,False,False
19,13,167.20000,21.00000,m45-303,62.118330,-25.385000,-1392.0,[offshore-(marine)],<NA>,[no],...,True,False,False,False,False,False,False,False,False,False
20,14,27.90000,12.80000,m45-305,61.720000,-24.541670,-1557.0,[offshore-(marine)],<NA>,[no],...,True,False,False,False,False,False,False,False,False,False
21,15,104.57600,-4.00000,frome 9,-31.690000,139.823000,111.0,[onshore-(continental)],mean hf,[no],...,False,False,True,False,False,False,False,False,False,False
22,16,128.05100,2.81700,frome 12,-31.597786,139.789707,92.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,False,False
23,17,110.00000,NaN,frome 15,35.500000,37.333333,111.0,[onshore-(continental)],<NA>,[no],...,False,False,True,False,False,False,False,False,False,True
24,18,98.00000,NaN,mans,42.500000,27.850000,150.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,False,True
25,19,85.00000,NaN,gediz,41.650000,28.200000,55.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,False,True
26,20,85.00000,NaN,gediz,40.990000,27.200000,63.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,False,True
27,21,78.00000,NaN,gsnbrg,41.650000,28.200000,111.0,[onshore-(continental)],<NA>,[no],...,False,False,False,False,False,False,False,False,False,True

In [13]:
df_checked = add_range_and_allowed_flags(df_data_typed, schema)

In [14]:
col = "P9"

# what was in your schema
allowed_raw = pd.Series(schema["columns"][col]["allowed"], dtype="string")

# normalized the same way as validator does
from etl.normalization import normalize_vocabulary_series
allowed_norm = normalize_vocabulary_series(allowed_raw)
allowed_set = {str(a).strip().lower() for a in allowed_norm.dropna()}

print("ALLOWED (canonical form):")
for a in sorted(allowed_set):
    print("  ", a)

print("\nDATA VALUES (first 20 distinct):")
print(df_checked[col].drop_duplicates().head(20).to_list())
df_checked.loc[df_checked["P9__invalid"], ["P9", "P9__invalid"]].head(20)

ALLOWED (canonical form):
   [no]
   [unspecified]
   [yes]

DATA VALUES (first 20 distinct):
['[no]', '[unspecified]', '[unspecifiedd]', <NA>]

                P9 P9__invalid
16  [unspecifiedd]        True